version: '3.2'
services:
  simple-app:
    build: ../
    environment:
      - PORT=8123
  cypress:
    image: "cypress/included:4.4.0"
    depends_on:
      - hello-world
    environment:
      - CYPRESS_baseUrl=http://simple-app:8123
    working_dir: /e2e
    volumes:
      - ./:/e2e
